Hotelier/Models/Hotel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Hotelier.Models {
    public class Hotel {
        public string Id { get; set; }
        public string CustomerId { get; set; }
    }
}

Hotelier/ViewModels/HotelCreateViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Hotelier.ViewModels {
    public class HotelCreateViewModel {
        public string Name { get; set; }
        public string Description { get; set; }
    }
}

Hotelier/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Raven.Client;

namespace Hotelier.Controllers {
    public class HomeController : Controller {
        public ActionResult Index() {
            return View();
        }
    }
}

Hotelier/Controllers/HotelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Hotelier.Controllers
{
    public class HotelsController : Controller
    {
        public ActionResult Create()
        {
            return View();
        }
    }
}

Hotelier/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Welcome to Hotelier</h2>
@Html.ActionLink("Set up your hotel now!", "Create", "Hotels")

Hotelier/Views/Hotels/Create.cshtml
@model Hotelier.ViewModels.HotelCreateViewModel
@{
    ViewBag.Title = "Create";
}

<h2>Tell us about your hotel</h2>
@using (Html.BeginForm()) {
  Html.EditorForModel();
  <input type="submit"/>
}